// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmcml.h"

extern XMcml_Config XMcml_ConfigTable[];

XMcml_Config *XMcml_LookupConfig(u16 DeviceId) {
	XMcml_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMCML_NUM_INSTANCES; Index++) {
		if (XMcml_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMcml_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMcml_Initialize(XMcml *InstancePtr, u16 DeviceId) {
	XMcml_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMcml_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMcml_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

