# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2015.4
# Copyright (C) 2015 Xilinx Inc. All rights reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XMcml" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_CTRL_REG_BASEADDR" \
        "C_S_AXI_CTRL_REG_HIGHADDR"

    xdefine_config_file $drv_handle "xmcml_g.c" "XMcml" \
        "DEVICE_ID" \
        "C_S_AXI_CTRL_REG_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XMcml" \
        "DEVICE_ID" \
        "C_S_AXI_CTRL_REG_BASEADDR" \
        "C_S_AXI_CTRL_REG_HIGHADDR"
}

