// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmcml.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMcml_CfgInitialize(XMcml *InstancePtr, XMcml_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_reg_BaseAddress = ConfigPtr->Ctrl_reg_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMcml_Start(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_AP_CTRL) & 0x80;
    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMcml_IsDone(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMcml_IsIdle(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMcml_IsReady(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMcml_EnableAutoRestart(XMcml *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_AP_CTRL, 0x80);
}

void XMcml_DisableAutoRestart(XMcml *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_AP_CTRL, 0);
}

void XMcml_Set_kernel_info_p_num_photons_i(XMcml *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NUM_PHOTONS_I_DATA, Data);
}

u32 XMcml_Get_kernel_info_p_num_photons_i(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NUM_PHOTONS_I_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_num_photons_o(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NUM_PHOTONS_O_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_num_photons_o_vld(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NUM_PHOTONS_O_CTRL);
    return Data & 0x1;
}

void XMcml_Set_kernel_info_p_dz_i(XMcml *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DZ_I_DATA, Data);
}

u32 XMcml_Get_kernel_info_p_dz_i(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DZ_I_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_dz_o(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DZ_O_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_dz_o_vld(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DZ_O_CTRL);
    return Data & 0x1;
}

void XMcml_Set_kernel_info_p_dr_i(XMcml *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DR_I_DATA, Data);
}

u32 XMcml_Get_kernel_info_p_dr_i(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DR_I_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_dr_o(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DR_O_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_dr_o_vld(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DR_O_CTRL);
    return Data & 0x1;
}

void XMcml_Set_kernel_info_p_da_i(XMcml *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DA_I_DATA, Data);
}

u32 XMcml_Get_kernel_info_p_da_i(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DA_I_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_da_o(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DA_O_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_da_o_vld(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_DA_O_CTRL);
    return Data & 0x1;
}

void XMcml_Set_kernel_info_p_nz_i(XMcml *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NZ_I_DATA, Data);
}

u32 XMcml_Get_kernel_info_p_nz_i(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NZ_I_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_nz_o(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NZ_O_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_nz_o_vld(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NZ_O_CTRL);
    return Data & 0x1;
}

void XMcml_Set_kernel_info_p_nr_i(XMcml *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NR_I_DATA, Data);
}

u32 XMcml_Get_kernel_info_p_nr_i(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NR_I_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_nr_o(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NR_O_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_nr_o_vld(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NR_O_CTRL);
    return Data & 0x1;
}

void XMcml_Set_kernel_info_p_na_i(XMcml *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NA_I_DATA, Data);
}

u32 XMcml_Get_kernel_info_p_na_i(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NA_I_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_na_o(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NA_O_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_na_o_vld(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NA_O_CTRL);
    return Data & 0x1;
}

void XMcml_Set_kernel_info_p_num_layers_i(XMcml *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NUM_LAYERS_I_DATA, Data);
}

u32 XMcml_Get_kernel_info_p_num_layers_i(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NUM_LAYERS_I_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_num_layers_o(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NUM_LAYERS_O_DATA);
    return Data;
}

u32 XMcml_Get_kernel_info_p_num_layers_o_vld(XMcml *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_KERNEL_INFO_P_NUM_LAYERS_O_CTRL);
    return Data & 0x1;
}

void XMcml_InterruptGlobalEnable(XMcml *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_GIE, 1);
}

void XMcml_InterruptGlobalDisable(XMcml *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_GIE, 0);
}

void XMcml_InterruptEnable(XMcml *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_IER);
    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_IER, Register | Mask);
}

void XMcml_InterruptDisable(XMcml *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_IER);
    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_IER, Register & (~Mask));
}

void XMcml_InterruptClear(XMcml *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMcml_WriteReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_ISR, Mask);
}

u32 XMcml_InterruptGetEnabled(XMcml *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_IER);
}

u32 XMcml_InterruptGetStatus(XMcml *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMcml_ReadReg(InstancePtr->Ctrl_reg_BaseAddress, XMCML_CTRL_REG_ADDR_ISR);
}

