#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/


/* Definitions for peripheral MICROBLAZE_0 */
#define XPAR_MICROBLAZE_0_ADDR_TAG_BITS 14
#define XPAR_MICROBLAZE_0_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_0_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_0_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_0_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_0_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_0_BASE_VECTORS 0x00000000
#define XPAR_MICROBLAZE_0_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_0_CACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_0_DATA_SIZE 32
#define XPAR_MICROBLAZE_0_DCACHE_ADDR_TAG 14
#define XPAR_MICROBLAZE_0_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_0_DCACHE_BASEADDR 0xC0000000
#define XPAR_MICROBLAZE_0_DCACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_0_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_0_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_0_DCACHE_HIGHADDR 0xDFFFFFFF
#define XPAR_MICROBLAZE_0_DCACHE_LINE_LEN 8
#define XPAR_MICROBLAZE_0_DCACHE_USE_WRITEBACK 1
#define XPAR_MICROBLAZE_0_DCACHE_VICTIMS 8
#define XPAR_MICROBLAZE_0_DC_AXI_MON 0
#define XPAR_MICROBLAZE_0_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_0_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_0_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_0_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_0_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_0_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_0_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_0_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_0_DP_AXI_MON 0
#define XPAR_MICROBLAZE_0_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_0_D_AXI 1
#define XPAR_MICROBLAZE_0_D_LMB 1
#define XPAR_MICROBLAZE_0_D_LMB_MON 0
#define XPAR_MICROBLAZE_0_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_0_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_0_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_0_ENDIANNESS 1
#define XPAR_MICROBLAZE_0_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_0_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_0_FREQ 100000000
#define XPAR_MICROBLAZE_0_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_0_FSL_LINKS 0
#define XPAR_MICROBLAZE_0_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_0_ICACHE_BASEADDR 0xC0000000
#define XPAR_MICROBLAZE_0_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_0_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_0_ICACHE_HIGHADDR 0xDFFFFFFF
#define XPAR_MICROBLAZE_0_ICACHE_LINE_LEN 8
#define XPAR_MICROBLAZE_0_ICACHE_STREAMS 1
#define XPAR_MICROBLAZE_0_ICACHE_VICTIMS 8
#define XPAR_MICROBLAZE_0_IC_AXI_MON 0
#define XPAR_MICROBLAZE_0_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_0_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_0_INTERCONNECT 2
#define XPAR_MICROBLAZE_0_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_0_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_0_IP_AXI_MON 0
#define XPAR_MICROBLAZE_0_I_AXI 0
#define XPAR_MICROBLAZE_0_I_LMB 1
#define XPAR_MICROBLAZE_0_I_LMB_MON 0
#define XPAR_MICROBLAZE_0_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_0_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_0_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_0_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_0_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_0_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_0_MMU_ZONES 2
#define XPAR_MICROBLAZE_0_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_0_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_0_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_0_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_0_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_0_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_0_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_0_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_0_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_0_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_0_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_0_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_0_OPTIMIZATION 0
#define XPAR_MICROBLAZE_0_PC_WIDTH 32
#define XPAR_MICROBLAZE_0_PVR 0
#define XPAR_MICROBLAZE_0_PVR_USER1 0x00
#define XPAR_MICROBLAZE_0_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_0_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_0_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_SCO 0
#define XPAR_MICROBLAZE_0_TRACE 0
#define XPAR_MICROBLAZE_0_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_0_USE_BARREL 1
#define XPAR_MICROBLAZE_0_USE_BRANCH_TARGET_CACHE 1
#define XPAR_MICROBLAZE_0_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_0_USE_DCACHE 1
#define XPAR_MICROBLAZE_0_USE_DIV 1
#define XPAR_MICROBLAZE_0_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_0_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_0_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_0_USE_FPU 2
#define XPAR_MICROBLAZE_0_USE_HW_MUL 2
#define XPAR_MICROBLAZE_0_USE_ICACHE 1
#define XPAR_MICROBLAZE_0_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_0_USE_MMU 0
#define XPAR_MICROBLAZE_0_USE_MSR_INSTR 1
#define XPAR_MICROBLAZE_0_USE_PCMP_INSTR 1
#define XPAR_MICROBLAZE_0_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_0_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_0_COMPONENT_NAME mb_system_microblaze_0_0
#define XPAR_MICROBLAZE_0_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_0_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_0_G_TEMPLATE_LIST 2
#define XPAR_MICROBLAZE_0_G_USE_EXCEPTIONS 0

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_MICROBLAZE_ID 0
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 14
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x00000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 14
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0xC0000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0xDFFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 8
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 1
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 8
#define XPAR_MICROBLAZE_DC_AXI_MON 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_DP_AXI_MON 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_D_LMB_MON 0
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0xC0000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0xDFFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 8
#define XPAR_MICROBLAZE_ICACHE_STREAMS 1
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 8
#define XPAR_MICROBLAZE_IC_AXI_MON 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_IP_AXI_MON 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_I_LMB_MON 0
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 2
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_USE_BARREL 1
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 1
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 1
#define XPAR_MICROBLAZE_USE_DIV 1
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 2
#define XPAR_MICROBLAZE_USE_HW_MUL 2
#define XPAR_MICROBLAZE_USE_ICACHE 1
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_MSR_INSTR 1
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 1
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME mb_system_microblaze_0_0
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 2
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 0

/******************************************************************/

#define STDIN_BASEADDRESS 0x41400000
#define STDOUT_BASEADDRESS 0x41400000

/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 13

/* Definitions for peripheral LAYERSPEC_CC0_CTRL */
#define XPAR_LAYERSPEC_CC0_CTRL_DEVICE_ID 0
#define XPAR_LAYERSPEC_CC0_CTRL_DATA_WIDTH 32
#define XPAR_LAYERSPEC_CC0_CTRL_ECC 0
#define XPAR_LAYERSPEC_CC0_CTRL_FAULT_INJECT 0
#define XPAR_LAYERSPEC_CC0_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_CC0_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_CC0_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_LAYERSPEC_CC0_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_LAYERSPEC_CC0_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_LAYERSPEC_CC0_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_LAYERSPEC_CC0_CTRL_WRITE_ACCESS 0
#define XPAR_LAYERSPEC_CC0_CTRL_S_AXI_BASEADDR 0xCC000000
#define XPAR_LAYERSPEC_CC0_CTRL_S_AXI_HIGHADDR 0xCC000FFF
#define XPAR_LAYERSPEC_CC0_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_LAYERSPEC_CC0_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral LAYERSPEC_CC1_CTRL */
#define XPAR_LAYERSPEC_CC1_CTRL_DEVICE_ID 1
#define XPAR_LAYERSPEC_CC1_CTRL_DATA_WIDTH 32
#define XPAR_LAYERSPEC_CC1_CTRL_ECC 0
#define XPAR_LAYERSPEC_CC1_CTRL_FAULT_INJECT 0
#define XPAR_LAYERSPEC_CC1_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_CC1_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_CC1_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_LAYERSPEC_CC1_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_LAYERSPEC_CC1_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_LAYERSPEC_CC1_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_LAYERSPEC_CC1_CTRL_WRITE_ACCESS 0
#define XPAR_LAYERSPEC_CC1_CTRL_S_AXI_BASEADDR 0xCE000000
#define XPAR_LAYERSPEC_CC1_CTRL_S_AXI_HIGHADDR 0xCE000FFF
#define XPAR_LAYERSPEC_CC1_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_LAYERSPEC_CC1_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral LAYERSPEC_G_CTRL */
#define XPAR_LAYERSPEC_G_CTRL_DEVICE_ID 2
#define XPAR_LAYERSPEC_G_CTRL_DATA_WIDTH 32
#define XPAR_LAYERSPEC_G_CTRL_ECC 0
#define XPAR_LAYERSPEC_G_CTRL_FAULT_INJECT 0
#define XPAR_LAYERSPEC_G_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_G_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_G_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_LAYERSPEC_G_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_LAYERSPEC_G_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_LAYERSPEC_G_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_LAYERSPEC_G_CTRL_WRITE_ACCESS 0
#define XPAR_LAYERSPEC_G_CTRL_S_AXI_BASEADDR 0xCA000000
#define XPAR_LAYERSPEC_G_CTRL_S_AXI_HIGHADDR 0xCA000FFF
#define XPAR_LAYERSPEC_G_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_LAYERSPEC_G_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral LAYERSPEC_MUA_CTRL */
#define XPAR_LAYERSPEC_MUA_CTRL_DEVICE_ID 3
#define XPAR_LAYERSPEC_MUA_CTRL_DATA_WIDTH 32
#define XPAR_LAYERSPEC_MUA_CTRL_ECC 0
#define XPAR_LAYERSPEC_MUA_CTRL_FAULT_INJECT 0
#define XPAR_LAYERSPEC_MUA_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_MUA_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_MUA_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_LAYERSPEC_MUA_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_LAYERSPEC_MUA_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_LAYERSPEC_MUA_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_LAYERSPEC_MUA_CTRL_WRITE_ACCESS 0
#define XPAR_LAYERSPEC_MUA_CTRL_S_AXI_BASEADDR 0xC6000000
#define XPAR_LAYERSPEC_MUA_CTRL_S_AXI_HIGHADDR 0xC6000FFF
#define XPAR_LAYERSPEC_MUA_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_LAYERSPEC_MUA_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral LAYERSPEC_MUS_CTRL */
#define XPAR_LAYERSPEC_MUS_CTRL_DEVICE_ID 4
#define XPAR_LAYERSPEC_MUS_CTRL_DATA_WIDTH 32
#define XPAR_LAYERSPEC_MUS_CTRL_ECC 0
#define XPAR_LAYERSPEC_MUS_CTRL_FAULT_INJECT 0
#define XPAR_LAYERSPEC_MUS_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_MUS_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_MUS_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_LAYERSPEC_MUS_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_LAYERSPEC_MUS_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_LAYERSPEC_MUS_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_LAYERSPEC_MUS_CTRL_WRITE_ACCESS 0
#define XPAR_LAYERSPEC_MUS_CTRL_S_AXI_BASEADDR 0xC8000000
#define XPAR_LAYERSPEC_MUS_CTRL_S_AXI_HIGHADDR 0xC8000FFF
#define XPAR_LAYERSPEC_MUS_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_LAYERSPEC_MUS_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral LAYERSPEC_N_CTRL */
#define XPAR_LAYERSPEC_N_CTRL_DEVICE_ID 5
#define XPAR_LAYERSPEC_N_CTRL_DATA_WIDTH 32
#define XPAR_LAYERSPEC_N_CTRL_ECC 0
#define XPAR_LAYERSPEC_N_CTRL_FAULT_INJECT 0
#define XPAR_LAYERSPEC_N_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_N_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_N_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_LAYERSPEC_N_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_LAYERSPEC_N_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_LAYERSPEC_N_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_LAYERSPEC_N_CTRL_WRITE_ACCESS 0
#define XPAR_LAYERSPEC_N_CTRL_S_AXI_BASEADDR 0xC4000000
#define XPAR_LAYERSPEC_N_CTRL_S_AXI_HIGHADDR 0xC4000FFF
#define XPAR_LAYERSPEC_N_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_LAYERSPEC_N_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral LAYERSPEC_Z0_CTRL */
#define XPAR_LAYERSPEC_Z0_CTRL_DEVICE_ID 6
#define XPAR_LAYERSPEC_Z0_CTRL_DATA_WIDTH 32
#define XPAR_LAYERSPEC_Z0_CTRL_ECC 0
#define XPAR_LAYERSPEC_Z0_CTRL_FAULT_INJECT 0
#define XPAR_LAYERSPEC_Z0_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_Z0_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_Z0_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_LAYERSPEC_Z0_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_LAYERSPEC_Z0_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_LAYERSPEC_Z0_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_LAYERSPEC_Z0_CTRL_WRITE_ACCESS 0
#define XPAR_LAYERSPEC_Z0_CTRL_S_AXI_BASEADDR 0xC0000000
#define XPAR_LAYERSPEC_Z0_CTRL_S_AXI_HIGHADDR 0xC0000FFF
#define XPAR_LAYERSPEC_Z0_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_LAYERSPEC_Z0_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral LAYERSPEC_Z1_CTRL */
#define XPAR_LAYERSPEC_Z1_CTRL_DEVICE_ID 7
#define XPAR_LAYERSPEC_Z1_CTRL_DATA_WIDTH 32
#define XPAR_LAYERSPEC_Z1_CTRL_ECC 0
#define XPAR_LAYERSPEC_Z1_CTRL_FAULT_INJECT 0
#define XPAR_LAYERSPEC_Z1_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_Z1_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_LAYERSPEC_Z1_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_LAYERSPEC_Z1_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_LAYERSPEC_Z1_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_LAYERSPEC_Z1_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_LAYERSPEC_Z1_CTRL_WRITE_ACCESS 0
#define XPAR_LAYERSPEC_Z1_CTRL_S_AXI_BASEADDR 0xC2000000
#define XPAR_LAYERSPEC_Z1_CTRL_S_AXI_HIGHADDR 0xC2000FFF
#define XPAR_LAYERSPEC_Z1_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_LAYERSPEC_Z1_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral MCML_STORE_ARZ_CTRL */
#define XPAR_MCML_STORE_ARZ_CTRL_DEVICE_ID 8
#define XPAR_MCML_STORE_ARZ_CTRL_DATA_WIDTH 32
#define XPAR_MCML_STORE_ARZ_CTRL_ECC 0
#define XPAR_MCML_STORE_ARZ_CTRL_FAULT_INJECT 0
#define XPAR_MCML_STORE_ARZ_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_MCML_STORE_ARZ_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_MCML_STORE_ARZ_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_MCML_STORE_ARZ_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_MCML_STORE_ARZ_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_MCML_STORE_ARZ_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_MCML_STORE_ARZ_CTRL_WRITE_ACCESS 0
#define XPAR_MCML_STORE_ARZ_CTRL_S_AXI_BASEADDR 0xD2000000
#define XPAR_MCML_STORE_ARZ_CTRL_S_AXI_HIGHADDR 0xD200FFFF
#define XPAR_MCML_STORE_ARZ_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_MCML_STORE_ARZ_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral MCML_STORE_RDRA_CTRL */
#define XPAR_MCML_STORE_RDRA_CTRL_DEVICE_ID 9
#define XPAR_MCML_STORE_RDRA_CTRL_DATA_WIDTH 32
#define XPAR_MCML_STORE_RDRA_CTRL_ECC 0
#define XPAR_MCML_STORE_RDRA_CTRL_FAULT_INJECT 0
#define XPAR_MCML_STORE_RDRA_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_MCML_STORE_RDRA_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_MCML_STORE_RDRA_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_MCML_STORE_RDRA_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_MCML_STORE_RDRA_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_MCML_STORE_RDRA_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_MCML_STORE_RDRA_CTRL_WRITE_ACCESS 0
#define XPAR_MCML_STORE_RDRA_CTRL_S_AXI_BASEADDR 0xD0000000
#define XPAR_MCML_STORE_RDRA_CTRL_S_AXI_HIGHADDR 0xD000FFFF
#define XPAR_MCML_STORE_RDRA_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_MCML_STORE_RDRA_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral MCML_STORE_TTRA_CTRL */
#define XPAR_MCML_STORE_TTRA_CTRL_DEVICE_ID 10
#define XPAR_MCML_STORE_TTRA_CTRL_DATA_WIDTH 32
#define XPAR_MCML_STORE_TTRA_CTRL_ECC 0
#define XPAR_MCML_STORE_TTRA_CTRL_FAULT_INJECT 0
#define XPAR_MCML_STORE_TTRA_CTRL_CE_FAILING_REGISTERS 0
#define XPAR_MCML_STORE_TTRA_CTRL_UE_FAILING_REGISTERS 0
#define XPAR_MCML_STORE_TTRA_CTRL_ECC_STATUS_REGISTERS 0
#define XPAR_MCML_STORE_TTRA_CTRL_CE_COUNTER_WIDTH 0
#define XPAR_MCML_STORE_TTRA_CTRL_ECC_ONOFF_REGISTER 0
#define XPAR_MCML_STORE_TTRA_CTRL_ECC_ONOFF_RESET_VALUE 0
#define XPAR_MCML_STORE_TTRA_CTRL_WRITE_ACCESS 0
#define XPAR_MCML_STORE_TTRA_CTRL_S_AXI_BASEADDR 0xD4000000
#define XPAR_MCML_STORE_TTRA_CTRL_S_AXI_HIGHADDR 0xD400FFFF
#define XPAR_MCML_STORE_TTRA_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_MCML_STORE_TTRA_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID 11
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 2
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x00007FFF
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID 12
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_FAULT_INJECT 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_WRITE_ACCESS 2
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_HIGHADDR 0x00007FFF
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFF 
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFF 


/******************************************************************/

/* Canonical definitions for peripheral LAYERSPEC_CC0_CTRL */
#define XPAR_BRAM_0_DEVICE_ID XPAR_LAYERSPEC_CC0_CTRL_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32
#define XPAR_BRAM_0_ECC 0
#define XPAR_BRAM_0_FAULT_INJECT 0
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_0_WRITE_ACCESS 0
#define XPAR_BRAM_0_BASEADDR 0xCC000000
#define XPAR_BRAM_0_HIGHADDR 0xCC000FFF

/* Canonical definitions for peripheral LAYERSPEC_CC1_CTRL */
#define XPAR_BRAM_1_DEVICE_ID XPAR_LAYERSPEC_CC1_CTRL_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32
#define XPAR_BRAM_1_ECC 0
#define XPAR_BRAM_1_FAULT_INJECT 0
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_1_WRITE_ACCESS 0
#define XPAR_BRAM_1_BASEADDR 0xCE000000
#define XPAR_BRAM_1_HIGHADDR 0xCE000FFF

/* Canonical definitions for peripheral LAYERSPEC_G_CTRL */
#define XPAR_BRAM_2_DEVICE_ID XPAR_LAYERSPEC_G_CTRL_DEVICE_ID
#define XPAR_BRAM_2_DATA_WIDTH 32
#define XPAR_BRAM_2_ECC 0
#define XPAR_BRAM_2_FAULT_INJECT 0
#define XPAR_BRAM_2_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_2_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_2_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_2_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_2_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_2_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_2_WRITE_ACCESS 0
#define XPAR_BRAM_2_BASEADDR 0xCA000000
#define XPAR_BRAM_2_HIGHADDR 0xCA000FFF

/* Canonical definitions for peripheral LAYERSPEC_MUA_CTRL */
#define XPAR_BRAM_3_DEVICE_ID XPAR_LAYERSPEC_MUA_CTRL_DEVICE_ID
#define XPAR_BRAM_3_DATA_WIDTH 32
#define XPAR_BRAM_3_ECC 0
#define XPAR_BRAM_3_FAULT_INJECT 0
#define XPAR_BRAM_3_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_3_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_3_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_3_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_3_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_3_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_3_WRITE_ACCESS 0
#define XPAR_BRAM_3_BASEADDR 0xC6000000
#define XPAR_BRAM_3_HIGHADDR 0xC6000FFF

/* Canonical definitions for peripheral LAYERSPEC_MUS_CTRL */
#define XPAR_BRAM_4_DEVICE_ID XPAR_LAYERSPEC_MUS_CTRL_DEVICE_ID
#define XPAR_BRAM_4_DATA_WIDTH 32
#define XPAR_BRAM_4_ECC 0
#define XPAR_BRAM_4_FAULT_INJECT 0
#define XPAR_BRAM_4_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_4_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_4_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_4_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_4_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_4_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_4_WRITE_ACCESS 0
#define XPAR_BRAM_4_BASEADDR 0xC8000000
#define XPAR_BRAM_4_HIGHADDR 0xC8000FFF

/* Canonical definitions for peripheral LAYERSPEC_N_CTRL */
#define XPAR_BRAM_5_DEVICE_ID XPAR_LAYERSPEC_N_CTRL_DEVICE_ID
#define XPAR_BRAM_5_DATA_WIDTH 32
#define XPAR_BRAM_5_ECC 0
#define XPAR_BRAM_5_FAULT_INJECT 0
#define XPAR_BRAM_5_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_5_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_5_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_5_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_5_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_5_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_5_WRITE_ACCESS 0
#define XPAR_BRAM_5_BASEADDR 0xC4000000
#define XPAR_BRAM_5_HIGHADDR 0xC4000FFF

/* Canonical definitions for peripheral LAYERSPEC_Z0_CTRL */
#define XPAR_BRAM_6_DEVICE_ID XPAR_LAYERSPEC_Z0_CTRL_DEVICE_ID
#define XPAR_BRAM_6_DATA_WIDTH 32
#define XPAR_BRAM_6_ECC 0
#define XPAR_BRAM_6_FAULT_INJECT 0
#define XPAR_BRAM_6_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_6_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_6_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_6_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_6_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_6_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_6_WRITE_ACCESS 0
#define XPAR_BRAM_6_BASEADDR 0xC0000000
#define XPAR_BRAM_6_HIGHADDR 0xC0000FFF

/* Canonical definitions for peripheral LAYERSPEC_Z1_CTRL */
#define XPAR_BRAM_7_DEVICE_ID XPAR_LAYERSPEC_Z1_CTRL_DEVICE_ID
#define XPAR_BRAM_7_DATA_WIDTH 32
#define XPAR_BRAM_7_ECC 0
#define XPAR_BRAM_7_FAULT_INJECT 0
#define XPAR_BRAM_7_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_7_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_7_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_7_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_7_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_7_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_7_WRITE_ACCESS 0
#define XPAR_BRAM_7_BASEADDR 0xC2000000
#define XPAR_BRAM_7_HIGHADDR 0xC2000FFF

/* Canonical definitions for peripheral MCML_STORE_ARZ_CTRL */
#define XPAR_BRAM_8_DEVICE_ID XPAR_MCML_STORE_ARZ_CTRL_DEVICE_ID
#define XPAR_BRAM_8_DATA_WIDTH 32
#define XPAR_BRAM_8_ECC 0
#define XPAR_BRAM_8_FAULT_INJECT 0
#define XPAR_BRAM_8_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_8_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_8_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_8_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_8_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_8_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_8_WRITE_ACCESS 0
#define XPAR_BRAM_8_BASEADDR 0xD2000000
#define XPAR_BRAM_8_HIGHADDR 0xD200FFFF

/* Canonical definitions for peripheral MCML_STORE_RDRA_CTRL */
#define XPAR_BRAM_9_DEVICE_ID XPAR_MCML_STORE_RDRA_CTRL_DEVICE_ID
#define XPAR_BRAM_9_DATA_WIDTH 32
#define XPAR_BRAM_9_ECC 0
#define XPAR_BRAM_9_FAULT_INJECT 0
#define XPAR_BRAM_9_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_9_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_9_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_9_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_9_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_9_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_9_WRITE_ACCESS 0
#define XPAR_BRAM_9_BASEADDR 0xD0000000
#define XPAR_BRAM_9_HIGHADDR 0xD000FFFF

/* Canonical definitions for peripheral MCML_STORE_TTRA_CTRL */
#define XPAR_BRAM_10_DEVICE_ID XPAR_MCML_STORE_TTRA_CTRL_DEVICE_ID
#define XPAR_BRAM_10_DATA_WIDTH 32
#define XPAR_BRAM_10_ECC 0
#define XPAR_BRAM_10_FAULT_INJECT 0
#define XPAR_BRAM_10_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_10_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_10_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_10_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_10_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_10_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_10_WRITE_ACCESS 0
#define XPAR_BRAM_10_BASEADDR 0xD4000000
#define XPAR_BRAM_10_HIGHADDR 0xD400FFFF

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_11_DEVICE_ID XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_11_DATA_WIDTH 32
#define XPAR_BRAM_11_ECC 0
#define XPAR_BRAM_11_FAULT_INJECT 0
#define XPAR_BRAM_11_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_11_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_11_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_11_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_11_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_11_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BRAM_11_WRITE_ACCESS 2
#define XPAR_BRAM_11_BASEADDR 0x00000000
#define XPAR_BRAM_11_HIGHADDR 0x00007FFF

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_12_DEVICE_ID XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_12_DATA_WIDTH 32
#define XPAR_BRAM_12_ECC 0
#define XPAR_BRAM_12_FAULT_INJECT 0
#define XPAR_BRAM_12_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_12_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_12_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_12_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_12_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_12_ECC_ONOFF_RESET_VALUE 1
#define XPAR_BRAM_12_WRITE_ACCESS 2
#define XPAR_BRAM_12_BASEADDR 0x00000000
#define XPAR_BRAM_12_HIGHADDR 0x00007FFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral GPIO_BTN */
#define XPAR_GPIO_BTN_BASEADDR 0x40010000
#define XPAR_GPIO_BTN_HIGHADDR 0x4001FFFF
#define XPAR_GPIO_BTN_DEVICE_ID 0
#define XPAR_GPIO_BTN_INTERRUPT_PRESENT 1
#define XPAR_GPIO_BTN_IS_DUAL 0


/* Definitions for peripheral GPIO_LED */
#define XPAR_GPIO_LED_BASEADDR 0x40000000
#define XPAR_GPIO_LED_HIGHADDR 0x4000FFFF
#define XPAR_GPIO_LED_DEVICE_ID 1
#define XPAR_GPIO_LED_INTERRUPT_PRESENT 0
#define XPAR_GPIO_LED_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral GPIO_BTN */
#define XPAR_GPIO_0_BASEADDR 0x40010000
#define XPAR_GPIO_0_HIGHADDR 0x4001FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_GPIO_BTN_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 1
#define XPAR_GPIO_0_IS_DUAL 0

/* Canonical definitions for peripheral GPIO_LED */
#define XPAR_GPIO_1_BASEADDR 0x40000000
#define XPAR_GPIO_1_HIGHADDR 0x4000FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_GPIO_LED_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 0


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 2
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_DEVICE_ID 0
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120FFFF
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0xFFFFFFFC
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_FAST 1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RESET_VALUE 0x00000010
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 2


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_MICROBLAZE_0_AXI_INTC_DEVICE_ID
#define XPAR_MICROBLAZE_0_AXI_INTC_TYPE 0
#define XPAR_GPIO_BTN_IP2INTC_IRPT_MASK 0X000001
#define XPAR_MICROBLAZE_0_AXI_INTC_GPIO_BTN_IP2INTC_IRPT_INTR 0
#define XPAR_MCML_0_INTERRUPT_MASK 0X000002
#define XPAR_MICROBLAZE_0_AXI_INTC_MCML_0_INTERRUPT_INTR 1

/******************************************************************/

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_MICROBLAZE_0_AXI_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000
#define XPAR_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFC
#define XPAR_INTC_0_HAS_FAST 1
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x00000010
#define XPAR_INTC_0_NUM_INTR_INPUTS 2
#define XPAR_INTC_0_INTC_TYPE 0

#define XPAR_INTC_0_GPIO_0_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_GPIO_BTN_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_MCML_0_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_MCML_0_INTERRUPT_INTR

/******************************************************************/

/* Definitions for driver MCML */
#define XPAR_XMCML_NUM_INSTANCES 1

/* Definitions for peripheral MCML_0 */
#define XPAR_MCML_0_DEVICE_ID 0
#define XPAR_MCML_0_S_AXI_CTRL_REG_BASEADDR 0x44A00000
#define XPAR_MCML_0_S_AXI_CTRL_REG_HIGHADDR 0x44A0FFFF


/******************************************************************/

/* Canonical definitions for peripheral MCML_0 */
#define XPAR_XMCML_0_DEVICE_ID XPAR_MCML_0_DEVICE_ID
#define XPAR_XMCML_0_S_AXI_CTRL_REG_BASEADDR 0x44A00000
#define XPAR_XMCML_0_S_AXI_CTRL_REG_HIGHADDR 0x44A0FFFF


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral MDM_1 */
#define XPAR_MDM_1_BASEADDR 0x41400000
#define XPAR_MDM_1_HIGHADDR 0x41400FFF
#define XPAR_MDM_1_DEVICE_ID 0
#define XPAR_MDM_1_BAUDRATE 0
#define XPAR_MDM_1_USE_PARITY 0
#define XPAR_MDM_1_ODD_PARITY 0
#define XPAR_MDM_1_DATA_BITS 0


/******************************************************************/

/* Canonical definitions for peripheral MDM_1 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_MDM_1_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x41400000
#define XPAR_UARTLITE_0_HIGHADDR 0x41400FFF
#define XPAR_UARTLITE_0_BAUDRATE 0
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 0


/******************************************************************/

#endif  /* end of protection macro */
